language: objective-c
osx_image: xcode8.3
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "KeychainCracker.xcodeproj" -scheme "KeychainCracker" build analyze | xcpretty
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
